name: CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest  # ✅ Explicitly install pytest

    - name: Verify pytest installation  # ✅ Debugging step
      run: |
        python -m pytest --version  # ✅ Check if pytest is installed

    - name: Run Tests
      run: |
        python -m pytest tests/test_app.py  # ✅ Use 'python -m pytest' instead of 'pytest'
